version: '3.1'

services:
  restoopdb:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: restoopdb
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
